# Generated by Django 4.1.4 on 2023-01-08 19:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(default='', max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('role', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullSequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sequence', models.TextField()),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('isCds', models.BooleanField(default=True)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacterial_genome_annotation.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gene', models.CharField(default='', max_length=10)),
                ('gene_biotype', models.CharField(default='', max_length=50)),
                ('transcript_biotype', models.CharField(default='', max_length=50)),
                ('gene_symbol', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=200)),
                ('transcript', models.CharField(default='', max_length=200)),
                ('isValidate', models.BooleanField(default=False)),
                ('annotator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotationForAnnotator', to=settings.AUTH_USER_MODEL)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotationForSequence', related_query_name='annotationQueryName', to='bacterial_genome_annotation.sequence')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotationForValidator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
