# Generated by Django 4.1.4 on 2023-01-04 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullSequence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phoneNumber', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('role', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sequence', models.TextField()),
                ('position', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('isCds', models.BooleanField(default=True)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacterial_genome_annotation.genome')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gene', models.CharField(default='', max_length=10)),
                ('gene_biotype', models.CharField(default='', max_length=50)),
                ('transcript_biotype', models.CharField(default='', max_length=50)),
                ('gene_symbol', models.CharField(default='', max_length=10)),
                ('description', models.CharField(default='', max_length=200)),
                ('isValidate', models.BooleanField(default=False)),
                ('annotator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotationForAnnotator', to='bacterial_genome_annotation.user')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacterial_genome_annotation.sequence')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotationForValidator', to='bacterial_genome_annotation.user')),
            ],
        ),
    ]
