# Generated by Django 4.1.4 on 2023-02-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blasthit',
            name='align_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='full',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='query',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='query_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='query_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blasthit',
            name='len',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blasthit',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
