# Generated by Django 4.1.4 on 2023-01-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='isAnwser',
            new_name='isAnswer',
        ),
    ]
