# Generated by Django 4.1.4 on 2023-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blasthit',
            name='subject_end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='subject_start',
            field=models.IntegerField(default=0),
        ),
    ]
