# Generated by Django 4.1.4 on 2023-01-16 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastResult',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('isCds', models.BooleanField(default=True)),
                ('numberOfResults', models.IntegerField(default=0)),
                ('isFinished', models.BooleanField(default=False)),
                ('sequence', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BlastHit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('definition', models.CharField(max_length=100)),
                ('accession', models.CharField(max_length=50)),
                ('len', models.IntegerField()),
                ('blastResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacterial_genome_annotation.blastresult')),
            ],
        ),
    ]
