# Generated by Django 4.1.4 on 2023-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='transcript',
            field=models.CharField(default='', max_length=200),
        ),
    ]
