# Generated by Django 4.1.4 on 2023-02-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0002_blasthit_align_length_blasthit_full_blasthit_query_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blasthit',
            name='gaps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='match',
            field=models.TextField(null=True),
        ),
    ]
