# Generated by Django 4.1.4 on 2023-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0002_rename_isanwser_comment_isanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='direction',
            field=models.BooleanField(default=True),
        ),
    ]
