# Generated by Django 4.1.4 on 2023-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0003_sequence_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='direction',
        ),
        migrations.AddField(
            model_name='blasthit',
            name='identitie',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
