# Generated by Django 4.1.4 on 2023-01-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0004_remove_sequence_direction_blasthit_identitie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blasthit',
            name='ident',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blasthit',
            name='lenn',
            field=models.IntegerField(null=True),
        ),
    ]
