# Generated by Django 4.1.4 on 2023-01-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacterial_genome_annotation', '0005_blasthit_ident_blasthit_lenn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blasthit',
            name='ident',
        ),
        migrations.RemoveField(
            model_name='blasthit',
            name='lenn',
        ),
    ]
